name: Dart

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "develop", "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603
      - name: Install dependencies
        run: dart pub get && sudo apt-get update -qq -y && sudo apt-get install lcov -y
      - name: Analyze project source
        run: dart analyze
      - name: Run tests
        run: flutter test integration_test/ --coverage && genhtml coverage/lcov.info -o coverage/html && open coverage/html/index.html
